
convo_starters = [
    "What's the most interesting thing you've read lately?",
    "What's a fact about you that you're most proud of?",
    "Do you listen to any podcasts? Which ones?",
    "If you were in charge of the playlist, which song would you play next?",
    "What's the best gift you've ever gotten?",
    f"What's your favorite part about living in your hometown?",
    "Are there any common misconceptions about your job?",
    "Why did you come chat?",
    "Are there any upcoming events you're planning on going to?",
    "What conference — real or imaginary — would you absolutely hate to miss?",
    "If you were giving a presentation, what would the topic be?",
    "I'm trying to plan my next trip — have you traveled anywhere interesting lately?",
]
food = [
    "Banana Cake",
    "Blueberry Coffee Cake",
    "Chocolate Cake",
    "Chocolate Mayonaise Cake",
    "Crazy Cake",
    "Fresh Apple Cake",
    "Fresh Pear Cake",
    "Graham Cracker Cake",
    "Hot Water Chocolate Cake",
    "Hungry Bear Cheese Cake",
    "Lemon Poppy Cake",
    "Light Old Fashioned Fruit Cake",
    "My Best Gingerbread",
    "Oatmeal Cake",
    "Orange Angel Food Cake",
    "Orange-Poppy Seed Pound Cake",
    "Pineapple Cake",
    "Pineapple-Carrot Cake*",
    "Potatoe Cake",
    "Pumpkin Swirl Cheesecake",
    "Refrigerator Cheesecake",
    "Sherry Wine Cake",
    "Special Prune Cake*",
    "Spicy Fruit and Nut Cake*",
    "Strawberry Spice Loaf",
    "Three Layer Chocolate Mayonnaise Cake",
    "Two Layer Chocolate Mayonnaise Cake",
    "Upside Down Cake",
    "Blue Chip Cookies",
    "Bourbon Balls",
    "Chocolate Crisp Bran Cookies",
    "Chocolate Peanut Brunch Bars",
    "Chocolate Trio Squares*",
    "Christmas Logs",
    "Christmas Snowballs",
    "Crisp Oatmeal Fruit Strips",
    "Frosted Delights",
    "Ginger Snap Bars",
    " Ginger Snaps",
    "Honey Graham Crackers",
    "Jello Pastel Cookies",
    "Lemon Squares",
    "Minties",
    "Oatmeal Cookies",
    "Oatmeal Fudge Bars*",
    "Peanut Butter Cookies",
    "Pineapple Graham Bars",
    "Prune Nut Bars",
    "Pumpkin Oatmeal Cookies",
    "Snickerdoodles",
    "Soft Sugar Cookies",
    "Thumbprint Cookies",
    "Walnut Squares",
    "Banana Cream Pie",
    "Blackberry Nectarine Pie",
    "Creamy Apple Pie",
    "Dutch Apple Pie",
    "Fresh Strawberry Pie",
    "Lemon Cloud Pie",
    "Lemon Luscious Pie",
    "Lemon Meringue Pie",
    "Old Fashioned Apple Pie",
    "Peach Almond Pie",
    "Peach Parfait Pie",
    "Peanut Butter Ice Cream Pie",
    "Peanut Butter Pie",
    "Pie Crust",
    "Sour Cream Raisin Pie",
    "Walnut Pie",
    "Walnut-Raisin pie",
    "Angel Hash",
    "Blue Cheese Dressing",
    "Broccoli Curry Salad",
    "Broccoli Salad",
    "Broccoli Salad with Pineapple",
    "Carrot Carousel",
    "Coleslaw",
    "Cranberry Mold",
    "Cucumbers in Sour Cream",
    "Five Bean Salad",
    "Five Cup Salad",
    "Garden Vegetable Pasta",
    "Green Bean Salad",
    "Heavenly Cheese Salad",
    "Horseradish Dressing",
    "Lemon Cloud Salad",
    "Lima Bean Salad",
    "Pea Salad",
    "School French Dressing",
    "Spinach Salad",
    "Spinach Salad with Avocado",
    "Spinach Salad with Alfalfa Sprouts",
    "Summer Fruit Salad",
    "Top Ramen Salad",
    "Zucchini Apple Slaw",
    "Broccoli Cheese Soup",
    "Chicken Noodle Soup",
    "Cleo's Clam Chowder",
    "Creamy Zucchini Mushroom Soup",
    "Elephant Stew",
    "Hungry Bear Vegetable Soup",
    "Mexican Meatball Soup",
    "Minestrone Soup",
    "Tortilla Soup",
    "Chicken and Shrimp Cantonese",
    "Chicken With Pineapple",
    "Chinese Beef",
    "Chinese Broccoli",
    "Chinese Chicken Salad",
    "Chinese Fried Rice",
    "Chinese Pepper Steak",
    "Chinese Roast Pork",
    "Chinese Stir Fried Chicken with Peanuts",
    "Scallops",
    "Cheese Fondue",
    "Golden Nugget Beef",
    "Baby Back Ribs",
    "Sweet and Sour Meatballs",
    "Saucy Shrimp Over Chinese Noodle Cakes",
    "Sole Thermidor",
    "Bake Trout",
    "Cheesy Fish Fillets with Spinach",
    "Cheese Fondue",
    "Sauteed Scallops",
    "'Louies' Linguini with Clam Sauce",
    "Sole Almondie",
    "Hot Crab Dip",
    "Shrimp Saute",
    "Sitr-Fry Beef and Broccoli",
    "Barbecued Spareribs",
    "Sweet and Sour Pork",
    "Beef Scallops with Fresh Tomato Sauce",
    "Veal Scallopini",
    "Savory Goulash",
    "Veal Parmigan",
    "Teriyaki Steak",
    "Beef Stroganoff",
    "Hungry Bear Cheese Cake",
    "Egg Foo Young",
    "Egg Roll Filling",
    "Egg Roll Wrappers",
    "Pineapple Spareribs",
    "Pork Fu Man Chow",
    "Shrimp Pineapple Fried Rice",
    "Sweet and Sour Pork",
    "Albert's Chicken",
    "Avocado Chicken Melt",
    "Batter Fried Chicken",
    "Catalina Chicken Stir Fry",
    "Chicken Breasts Florentine",
    "Chicken Cashew",
    "Chicken Lo Mein",
    "Chicken Paprika",
    "Chicken Schnitzel",
    "Chicken with Artichoke",
    "Coq au Vin",
    "Creamy Chicken Broccoli with Rice",
    "In a Hurry Chicken Curry",
    "Jack Zucchini Chicken",
    "nan",
    "Maryland Fried Chicken",
    "Oven Fried Chicken",
    "Parsley and Parmasen Baked Chicken",
    "Sandra's 'Tree Trimmer' Chicken",
    "Saute'd Chicken Breats",
    "Saute'd Chicken Livers",
    "Spicy Singapore Wings",
    "Turkey Tenderloin Supreme",
    "Asparagus Stir-Fried",
    "Baked Green Beans",
    "Baked Zucchini with Mushrooms",
    "Bit O' Zucchini Bites",
    "Cheesy Spinach Bake",
    "Company Cabbage",
    "Crisp Potato Pancakes",
    "Easy Oven Baked Potatoes",
    "Eggplant Rollatini",
    "Glazed Carrots",
    "Green Beans Salerno",
    "Italian Zucchini",
    "Mushrooms in Sour Cream",
    "Orange Sweet Potatoes",
    "Peas",
    "Saute Zucchini",
    "Spinach Pie",
    "Spinach Souffle",
    "Spinach Strudels",
    "Stuffed Zucchini",
    "Summer Squash",
    "Sweet and Sour Red Cabbage",
    "The Spinach",
    "Three Cheese Spinach",
    "Tulelake Potato Casserole",
    "Zucchini Patties",
    "Apple Dumplings",
    "Apple Dessert for a Crowd",
    "Chilled Prune Whip",
    "Fresh Peach Dessert",
    "South Carolina Cobbler",
    "Spanish Cream Pudding",
    "Artichoke-Mozzarella Casserole",
    "Asparagus Tomato Quiche",
    "Beef Enchiladas",
    "Beef Spinach Quiche",
    "Broccoli and Rice Casserole",
    "Broccoli Cheese Pie",
    "Cheese Strata",
    "Chicken Tamale Pie",
    "Chili Cheese Puff",
    "Chili Chicken",
    "Chinese Noodle Casserole",
    "Crazy Crust Pizza",
    "Deep Dish Pizza",
    "Easy Pasta Bake",
    "Fum Gum",
    "Garden Quiche",
    "Impossible Taco Pie",
    "Pasta Primavera",
    "Ranch-style Baked Beans",
    "Savory Chicken Casserole",
    "Sour Cream Enchiladas",
    "Spinach Fritatta",
    "Stuffed Green Peppers",
    "Tamale Pie",
    "Tulelake Potato Casserole",
    "Wild Mushroom and Spinach Lasanga",
    "Zucchini Casserole",
    "Zucchini-Ham Cheese Pie",
]
academic = [
    "general agriculture",
    "agriculture production and management",
    "agricultural economics",
    "animal sciences",
    "food science",
    "plant science and agronomy",
    "soil science",
    "miscellaneous agriculture",
    "forestry",
    "natural resources management",
    "fine arts",
    "drama and theater arts",
    "music",
    "visual and performing arts",
    "commercial art and graphic design",
    "film video and photographic arts",
    "studio arts",
    "miscellaneous fine arts",
    "environmental science",
    "biology",
    "biochemical sciences",
    "botany",
    "molecular biology",
    "ecology",
    "genetics",
    "microbiology",
    "pharmacology",
    "physiology",
    "zoology",
    "neuroscience",
    "miscellaneous biology",
    "cognitive science and biopsychology",
    "general business",
    "accounting",
    "actuarial science",
    "business management and administration",
    "operations logistics and e-commerce",
    "business economics",
    "marketing and marketing research",
    "finance",
    "human resources and personnel management",
    "international business",
    "hospitality management",
    "management information systems and statistics",
    "miscellaneous business & medical administration",
    "communications",
    "journalism",
    "mass media",
    "advertising and public relations",
    "communication technologies",
    "computer and information systems",
    "computer programming and data processing",
    "computer science",
    "information sciences",
    "computer administration management and security",
    "computer networking and telecommunications",
    "mathematics",
    "applied mathematics",
    "statistics and decision science",
    "mathematics and computer science",
    "general education",
    "educational administration and supervision",
    "school student counseling",
    "elementary education",
    "mathematics teacher education",
    "physical and health education teaching",
    "early childhood education",
    "science and computer teacher education",
    "secondary teacher education",
    "special needs education",
    "social science or history teacher education",
    "teacher education: multiple levels",
    "language and drama education",
    "art and music education",
    "miscellaneous education",
    "library science",
    "architecture",
    "general engineering",
    "aerospace engineering",
    "biological engineering",
    "architectural engineering",
    "biomedical engineering",
    "chemical engineering",
    "civil engineering",
    "computer engineering",
    "electrical engineering",
    "engineering mechanics physics and science",
    "environmental engineering",
    "geological and geophysical engineering",
    "industrial and manufacturing engineering",
    "materials engineering and materials science",
    "mechanical engineering",
    "metallurgical engineering",
    "mining and mineral engineering",
    "naval architecture and marine engineering",
    "nuclear engineering",
    "petroleum engineering",
    "miscellaneous engineering",
    "engineering technologies",
    "engineering and industrial management",
    "electrical engineering technology",
    "industrial production technologies",
    "mechanical engineering related technologies",
    "miscellaneous engineering technologies",
    "materials science",
    "nutrition sciences",
    "general medical and health services",
    "communication disorders sciences and services",
    "health and medical administrative services",
    "medical assisting services",
    "medical technologies technicians",
    "health and medical preparatory programs",
    "nursing",
    "pharmacy pharmaceutical sciences and administration",
    "treatment therapy professions",
    "community and public health",
    "miscellaneous health medical professions",
    "area ethnic and civilization studies",
    "linguistics and comparative language and literature",
    "french german latin and other common foreign language studies",
    "other foreign languages",
    "english language and literature",
    "composition and rhetoric",
    "liberal arts",
    "humanities",
    "intercultural and international studies",
    "philosophy and religious studies",
    "theology and religious vocations",
    "anthropology and archeology",
    "art history and criticism",
    "history",
    "united states history",
    "cosmetology services and culinary arts",
    "family and consumer sciences",
    "military technologies",
    "physical fitness parks recreation and leisure",
    "construction services",
    "electrical, mechanical, and precision technologies and production",
    "transportation sciences and technologies",
    "multi/interdisciplinary studies",
    "court reporting",
    "pre-law and legal studies",
    "criminal justice and fire protection",
    "public administration",
    "public policy",
    "n/a (less than bachelor's degree)",
    "physical sciences",
    "astronomy and astrophysics",
    "atmospheric sciences and meteorology",
    "chemistry",
    "geology and earth science",
    "geosciences",
    "oceanography",
    "physics",
    "multi-disciplinary or general science",
    "nuclear, industrial radiology, and biological technologies",
    "psychology",
    "educational psychology",
    "clinical psychology",
    "counseling psychology",
    "industrial and organizational psychology",
    "social psychology",
    "miscellaneous psychology",
    "human services and community organization",
    "social work",
    "interdisciplinary social sciences",
    "general social sciences",
    "economics",
    "criminology",
    "geography",
    "international relations",
    "political science and government",
    "sociology",
    "miscellaneous social sciences",
]
celebs = [
    "Marilyn Monroe",
    "Abraham Lincoln",
    "Mother Teresa",
    "John F. Kennedy",
    "Martin Luther King",
    "Nelson Mandela",
    "Winston Churchill",
    "Bill Gates",
    "Muhammad Ali",
    "Mahatma Gandhi",
    "Margaret Thatcher",
    "Charles de Gaulle",
    "Christopher Columbus",
    "George Orwell",
    "Charles Darwin",
    "Elvis Presley",
    "Albert Einstein",
    "Paul McCartney",
    "Plato",
    "Queen Elizabeth II",
    "Queen Victoria",
    "John M Keynes",
    "Mikhail Gorbachev",
    "Jawaharlal Nehru",
    "Leonardo da Vinci",
    "Louis Pasteur",
    "Leo Tolstoy",
    "Pablo Picasso",
    "Vincent Van Gogh",
    "Franklin D. Roosevelt",
    "Pope John Paul II",
    "Thomas Edison",
    "Rosa Parks",
    "Aung San Suu Kyi",
    "Lyndon Johnson",
    "Ludwig Beethoven",
    "Oprah Winfrey",
    "Indira Gandhi",
    "Eva Peron",
    "Benazir Bhutto",
    "Desmond Tutu",
    "Dalai Lama",
    "Walt Disney",
    "Neil Armstrong",
    "Peter Sellers",
    "Barack Obama",
    "Malcolm X",
    "J.K.Rowling",
    "Richard Branson",
    "Pele",
    "Angelina Jolie",
    "Jesse Owens",
    "Ernest Hemingway",
    "John Lennon",
    "Henry Ford",
    "Haile Selassie",
    "Joseph Stalin",
    "Lord Baden Powell",
    "Michael Jordon",
    "George Bush jnr",
    "V.Lenin",
    "Ingrid Bergman",
    "Fidel Castro",
    "Oscar Wilde",
    "Coco Chanel",
    "Pope Francis",
    "Amelia Earhart",
    "Sting",
    "Mary Magdalene",
    "Alfred Hitchcock",
    "Michael Jackson",
    "Madonna",
    "Mata Hari",
    "Cleopatra",
    "Grace Kelly",
    "Steve Jobs",
    "Ronald Reagan",
    "Lionel Messi",
    "Babe Ruth",
    "Bob Geldof",
    "Leon Trotsky",
    "Roger Federer",
    "Sigmund Freud",
    "Woodrow Wilson",
    "Mao Zedong",
    "Katherine Hepburn",
    "Audrey Hepburn",
    "David Beckham",
    "Tiger Woods",
    "Usain Bolt",
    "Carl Lewis",
    "Prince Charles",
    "Jacqueline Kennedy Onassis",
    "C.S. Lewis",
    "Billie Holiday",
    "J.R.R. Tolkien",
    "Tom Cruise",
    "Billie Jean King",
    "Anne Frank",
    "Simon Bolivar",
    "Marie Antoinette",
    "Christiano Ronaldo",
    "Emmeline Pankhurst ",
    "Emile Zatopek",
    "Lech Walesa",
    "Julie Andrews",
    "Florence Nightingale",
    "Marie Curie",
    "Stephen Hawking",
    "Tim Berners Lee",
    "Lance Armstrong",
    "Shakira",
    "Jon Stewart",
    "Wright Brothers",
    "Roman Abramovich",
    "Rupert Murdoch",
    "Al Gore",
    "Sacha Baron Cohen",
    "George Clooney",
    "Paul Krugman",
    "Jimmy Wales",
    "Brad Pitt",
    "Kylie Minogue",
    "Malala Yousafzai",
    "Stephen King",
]
sports = [
    "soccer",
    "basketball",
    "tennis",
    "baseball",
    "golf",
    "running",
    "volleyball",
    "badminton",
    "swimming",
    "boxing",
    "table tennis",
    "skiing",
    "ice skating",
    "roller skating",
    "cricket",
    "rugby",
    "pool",
    "darts",
    "football",
    "bowling",
    "ice hockey",
    "surfing",
    "karate",
    "horse racing",
    "snowboarding",
    "skateboarding",
    "cycling",
    "archery",
    "fishing",
    "gymnastics",
    "figure skating",
    "rock climbing",
    "sumo wrestling",
    "taekwondo",
    "fencing",
    "water skiing",
    "jet skiing",
    "weight lifting",
    "scuba diving",
    "judo",
    "wind surfing",
    "kickboxing",
    "sky diving",
    "hang gliding",
    "bungee jumping",
]
books = [
    "Twilight",
    "The Hunger Games",
    "Path Finder",
    "The Knife Itself",
    "The Wheel of Time",
    "The Gift of Time",
    "Sapiens, A Brief History of Mankind",
    "Why We Sleep",
    "Fundamentals of Wavelets",
    "Data Smart",
    "God Created the Integers",
    "Superfreakonomics",
    "Orientalism",
    "Nature of Statistical Learning Theory, The",
    "Integration of the Indian States",
    "Drunkard's Walk, The",
    "Image Processing & Mathematical Morphology",
    "How to Think Like Sherlock Holmes",
    "Data Scientists at Work",
    "Slaughterhouse Five",
    "Birth of a Theorem",
    "Structure & Interpretation of Computer Programs",
    "The Age of Wrath",
    "Trial, The",
    "Statistical Decision Theory'",
    "Data Mining Handbook",
    "New Machiavelli, The",
    "Physics & Philosophy",
    "Making Software",
    "Analysis, Vol I",
    "Machine Learning for Hackers",
    "Signal and the Noise, The",
    "Python for Data Analysis",
    "Introduction to Algorithms",
    "Beautiful and the Damned, The",
    "Outsider, The",
    "Complete Sherlock Holmes, The - Vol I",
    "Complete Sherlock Holmes, The - Vol II",
    "Wealth of Nations, The",
    "Pillars of the Earth, The",
    "Mein Kampf",
    "Tao of Physics, The",
    "Surely You're Joking Mr Feynman",
    "Farewell to Arms, A",
    "Veteran, The",
    "False Impressions",
    "Last Lecture, The",
    "Return of the Primitive",
    "Jurassic Park",
    "Russian Journal, A",
    "Tales of Mystery and Imagination",
    "Freakonomics",
    "Hidden Connections, The",
    "Story of Philosophy, The",
    "Asami Asami",
    "Journal of a Novel",
    "Once There Was a War",
    "Moon is Down, The",
    "Brethren, The",
    "In a Free State",
    "Catch 22",
    "Complete Mastermind, The",
    "Dylan on Dylan",
    "Soft Computing & Intelligent Systems",
    "Textbook of Economic Theory",
    "Econometric Analysis",
    "Learning OpenCV",
    "Data Structures Using C & C++",
    "Computer Vision, A Modern Approach",
    "Principles of Communication Systems",
    "Let Us C",
    "Amulet of Samarkand, The",
    "Crime and Punishment",
    "Angels & Demons",
    "Argumentative Indian, The",
    "Sea of Poppies",
    "Idea of Justice, The",
    "Raisin in the Sun, A",
    "All the President's Men",
    "Prisoner of Birth, A",
    "Scoop!",
    "Ahe Manohar Tari",
    "Last Mughal, The",
    "Social Choice & Welfare, Vol 39 No. 1",
    "Radiowaril Bhashane & Shrutika",
    "Gun Gayin Awadi",
    "Aghal Paghal",
    "Maqta-e-Ghalib",
    "Beyond Degrees",
    "Manasa",
    "India from Midnight to Milennium",
    "World's Greatest Trials, The",
    "Great Indian Novel, The",
    "O Jerusalem!",
    "City of Joy, The",
    "Freedom at Midnight",
    "Winter of Our Discontent, The",
    "On Education",
    "Free Will",
    "Bookless in Baghdad",
    "Case of the Lame Canary, The",
    "Theory of Everything, The",
    "New Markets & Other Essays",
    "Electric Universe",
    "Hunchback of Notre Dame, The",
    "Burning Bright",
    "Age of Discontuinity, The",
    "Doctor in the Nude",
    "Down and Out in Paris & London",
    "Identity & Violence",
    "Beyond the Three Seas",
    "World's Greatest Short Stories, The",
    "Talking Straight",
    "Maugham's Collected Short Stories, Vol 3",
    "Phantom of Manhattan, The",
    "Ashenden of The British Agent",
    "Zen & The Art of Motorcycle Maintenance",
    "Great War for Civilization, The",
    "We the Living",
    "Artist and the Mathematician, The",
    "History of Western Philosophy",
    "Selected Short Stories",
    "Rationality & Freedom",
    "Clash of Civilizations and Remaking of the World Order",
    "Uncommon Wisdom",
    "One",
    "Karl Marx Biography",
    "To Sir With Love",
    "Half A Life",
    "Discovery of India, The",
    "Apulki",
    "Unpopular Essays",
    "Deceiver, The",
    "Veil: Secret Wars of the CIA",
    "Char Shabda",
    "Rosy is My Relative",
    "Moon and Sixpence, The",
    "Political Philosophers",
    "Short History of the World, A",
    "Trembling of a Leaf, The",
    "Doctor on the Brain",
    "Simpsons & Their Mathematical Secrets",
    "Pattern Classification",
    "From Beirut to Jerusalem",
    "Code Book, The",
    "Age of the Warrior, The",
    "Final Crisis",
    "Killing Joke, The",
    "Flashpoint",
    "Batman Earth One",
    "Crisis on Infinite Earths",
    "Numbers Behind Numb3rs, The",
    "Superman Earth One - 1",
    "Superman Earth One - 2",
    "Justice League: Throne of Atlantis",
    "Justice League: The Villain's Journey",
    "Death of Superman, The",
    "History of the DC Universe",
    "Batman: The Long Halloween",
    "A Life in Letters",
    "The Information",
    "Journal of Economics, vol 106 No 3",
    "Elements of Information Theory",
    "Power Electronics - Rashid",
    "Power Electronics - Mohan",
    "Neural Networks",
    "Grapes of Wrath, The",
    "Vyakti ani Valli",
    "Statistical Learning Theory",
    "Empire of the Mughal - The Tainted Throne",
    "Empire of the Mughal - Brothers at War",
    "Empire of the Mughal - Ruler of the World",
    "Empire of the Mughal - The Serpent's Tooth",
    "Empire of the Mughal - Raiders from the North",
    "Mossad",
    "Jim Corbett Omnibus",
    "20000 Leagues Under the Sea",
    "Batatyachi Chal",
    "Hafasavnuk",
    "Urlasurla",
    "Pointers in C",
    "The Cathedral and the Bazaar",
    "Design with OpAmps",
    "Think Complexity",
    "The Devil's Advocate",
    "Ayn Rand Answers",
    "Philosophy: Who Needs It",
    "World's Great Thinkers, The",
    "Data Analysis with Open Source Tools",
    "Broca's Brain",
    "Men of Mathematics",
    "Oxford book of Modern Science Writing",
    "Justice, Judiciary and Democracy",
    "The Arthashastra",
    "We the People",
    "We the Nation",
    "The Courtroom Genius",
    "Dongri to Dubai",
    "History of England, Foundation",
    "City of Djinns",
    "India's Legal System",
    "More Tears to Cry",
    "The Ropemaker",
    "Angels & Demons",
    "The Judge",
    "The Attorney",
    "The Prince",
    "Eyeless in Gaza",
    "Tales of Beedle the Bard",
    "Girl with the Dragon Tattoo",
    "Girl who kicked the Hornet's Nest",
    "Girl who played with Fire",
    "Batman Handbook",
    "Murphy's Law",
    "Structure and Randomness",
    "Image Processing with MATLAB",
    "Animal Farm",
    "The Idiot",
    "A Christmas Carol",
]
movies = [
    "Youth in Revolt",
    "You Will Meet a Tall Dark Stranger",
    "When in Rome",
    "What Happens in Vegas",
    "Water For Elephants",
    "WALL-E",
    "Waitress",
    "Waiting For Forever",
    "Valentine's Day",
    "Tyler Perry's Why Did I get Married",
    "Twilight: Breaking Dawn",
    "Twilight",
    "The Ugly Truth",
    "The Twilight Saga: New Moon",
    "The Time Traveler's Wife",
    "The Proposal",
    "The Invention of Lying",
    "The Heartbreak Kid",
    "The Duchess",
    "The Curious Case of Benjamin Button",
    "The Back-up Plan",
    "Tangled",
    "Something Borrowed",
    "She's Out of My League",
    "Sex and the City Two",
    "Sex and the City 2",
    "Sex and the City",
    "Remember Me",
    "Rachel Getting Married",
    "Penelope",
    "P.S. I Love You",
    "Over Her Dead Body",
    "Our Family Wedding",
    "One Day",
    "Not Easily Broken",
    "No Reservations",
    "Nick and Norah's Infinite Playlist",
    "New Year's Eve",
    "My Week with Marilyn",
    "Music and Lyrics",
    "Monte Carlo",
    "Miss Pettigrew Lives for a Day",
    "Midnight in Paris",
    "Marley and Me",
    "Mamma Mia!",
    "Made of Honor",
    "Love Happens",
    "Love & Other Drugs",
    "Life as We Know It",
    "License to Wed",
    "Letters to Juliet",
    "Leap Year",
    "Knocked Up",
    "Killers",
    "Just Wright",
    "Jane Eyre",
    "It's Complicated",
    "I Love You Phillip Morris",
    "High School Musical 3: Senior Year",
    "He's Just Not That Into You",
    "Good Luck Chuck",
    "Going the Distance",
    "Gnomeo and Juliet",
    "Ghosts of Girlfriends Past",
    "Four Christmases",
    "Fireproof",
    "Everything, Everywhere, all at Once",
    "Enchanted",
    "Dear John",
    "Beginners",
    "Across the Universe",
    "A Serious Man",
    "A Dangerous Method",
    "27 Dresses",
    "(500) Days of Summer",
]
tv_shows = [
    "White Chicks",
    "Lucky Number Slevin",
    "Grey's Anatomy",
    "Prison Break",
    "How I Met Your Mother",
    "Supernatural",
    "Breaking Bad",
    "The Vampire Diaries",
    "The Walking Dead",
    "Pretty Little Liars",
    "Once Upon a Time",
    "Sherlock",
    "Death Note",
    "Naruto",
    "The Hunter",
    "Lottie Dottie Chicken",
    "Arrow",
    "Black Mirror",
    "The Originals",
    "The 100",
    "Masha and the Bear",
    "Ã“ Pai, Ã“ - Look at This",
    "Nymphomaniac: Volume 1",
    "Hunter X Hunter (2011)",
    "Marvel's Luke Cage",
    "Marvel's Iron Fist",
    "Narcos",
    "The Flash",
    "The Seven Deadly Sins",
    "Scream",
    "The Do-Over",
    "OperaÃ§Ãµes Especiais",
    "0.03",
    "Trollhunters",
    "Fearless",
    "Hyena Road",
    "Santa Clarita Diet",
    "Sex, Love and Therapy",
    "White Girl",
    "Girlboss",
    "City of God: 10 Years Later",
    "13 Reasons Why",
    "Sand Castle",
    "Salvador Martinha - Tip of the Tongue",
    "Sandy Wexler",
    "O Amor no DivÃ£",
    "Stronger Than the World",
    "Back and Forth",
    "Happily Married",
    "Pandora",
    "Lucky Number Slevin",
    "The Office (U.S.)",
    "Grey's Anatomy",
    "Prison Break",
    "90210",
    "Gossip Girl",
    "How I Met Your Mother",
    "Supernatural",
    "Breaking Bad",
    "Parks and Recreation",
    "Glee",
    "The Vampire Diaries",
    "Family Guy",
    "Criminal Minds",
    "Friends",
    "The Secret Life of the American Teenager",
    "One Tree Hill",
    "The Walking Dead",
    "Pretty Little Liars",
    "Shameless (U.S.)",
    "New Girl",
    "American Horror Story",
    "Orange Is the New Black",
    "Inside Russia's Toughest Prison",
    "Black Mirror",
    "Bates Motel",
    "The 100",
    "Marvel's Iron Fist",
    "Grace and Frankie",
    "How to Get Away with Murder",
    "The Get Down",
    "Love",
    "The Flash",
    "The OA",
    "Stranger Things",
    "Ingobernable",
    "Zootopia",
    "Meet the Blacks",
    "Finding Dory",
    "Santa Clarita Diet",
    "Sausage Party",
    "Pete's Dragon",
    "Kevin Hart: What Now?",
    "Girlboss",
    "The Discovery",
    "Sand Castle",
    "Sandy Wexler",
    "Chewing Gum",
    "Cheer Squad",
    "Only for One Night",
    "The Life Aquatic with Steve Zissou",
    "Lucky Number Slevin",
    "The L Word",
    "The Office (U.S.)",
    "30 Rock",
    "Mad Men",
    "It's Always Sunny in Philadelphia",
    "Californication",
    "Parks and Recreation",
    "Friends",
    "Shameless (U.S.)",
    "Portlandia",
    "New Girl",
    "Don't Trust the B---- in Apartment 23",
    "Friends with Benefits",
    "The Client List",
    "Halt and Catch Fire",
    "5 to 7",
    "Marvel's Iron Fist",
    "Chef's Table",
    "Documentary Now!",
    "Grace and Frankie",
    "Better Call Saul",
    "The Get Down",
    "Schitt's Creek",
    "Lovesick",
    "Flaked",
    "Master of None",
    "Chelsea",
    "Abstract: The Art of Design",
    "Cooper Barrett's Guide to Surviving Life",
    "The Great British Baking Show",
    "Life in Pieces",
    "Crazy Ex-Girlfriend",
    "Easy",
    "Santa Clarita Diet",
    "No Tomorrow",
    "Minimalism: A Documentary About the Important Things",
    "Girlboss",
    "Hot Girls Wanted: Turned On",
    "The Discovery",
    "13 Reasons Why",
    "Sandy Wexler",
    "Chewing Gum",
    "Win It All",
    "MerlÃ­",
    "Amy Schumer: The Leather Special",
    "Louis C.K. 2017",
    "Dave Chappelle",
    "Almost Adults",
    "The Brothers",
    "Skins",
    "The Cleveland Show",
    "Absolutely Fabulous",
    "Don't Trust the B---- in Apartment 23",
    "Raising Hope",
    "Come Fly With Me",
    "Orange Is the New Black",
    "Brickleberry",
    "Bates Motel",
    "BoJack Horseman",
    "Being Mary Jane: The Series",
    "Documentary Now!",
    "Grace and Frankie",
    "Unbreakable Kimmy Schmidt",
    "The Get Down",
    "Love",
    "Bordertown",
    "Jane The Virgin",
    "Schitt's Creek",
    "Dope",
    "Lovesick",
    "The Carmichael Show",
    "Cooper Barrett's Guide to Surviving Life",
    "The Great British Baking Show",
    "November Rule",
    "Life in Pieces",
    "Crazy Ex-Girlfriend",
    "Easy",
    "Haters Back Off",
    "Kubo and the Two Strings",
    "Skins",
    "A Weekend with the Family",
    "Crazyhead",
    "Queen of Katwe",
    "Little Boxes",
    "Deidra & Laney Rob a Train",
    "Girlboss",
    "Hot Girls Wanted: Turned On",
    "13 Reasons Why",
    "Hurricane Bianca",
    "Honeytrap",
    "Greenleaf",
    "Lazy Eye",
    "Like Cotton Twines",
    "The Wedding Party",
    "Dave Chappelle",
    "Only for One Night",
    "Boy Bye",
    "Almost Adults",
    "Nancy Drew",
    "30 Rock",
    "Nurse Jackie",
    "Parks and Recreation",
    "Drop Dead Diva",
    "Gilmore Girls",
    "Parenthood",
    "Life Unexpected",
    "Portlandia",
    "New Girl",
    "Don't Trust the B---- in Apartment 23",
    "Raising Hope",
    "Being Human (U.S.)",
    "Friends with Benefits",
    "The Carrie Diaries",
    "Baby Daddy",
    "Halt and Catch Fire",
    "The Angriest Man in Brooklyn",
    "5 to 7",
    "Chef's Table",
    "Grace and Frankie",
    "Unbreakable Kimmy Schmidt",
    "The Get Down",
    "Sense8",
    "Love",
    "Bordertown",
    "Girlfriends' Guide to Divorce",
    "Schitt's Creek",
    "The Carmichael Show",
    "Chelsea",
    "Abstract: The Art of Design",
    "Cooper Barrett's Guide to Surviving Life",
    "The Great British Baking Show",
    "Life in Pieces",
    "Crazy Ex-Girlfriend",
    "Fried",
    "The Great Gilly Hopkins",
    "The Magicians",
    "One Day at a Time",
    "No Tomorrow",
    "Hot Girls Wanted: Turned On",
    "13 Reasons Why",
    "Better Off Single",
    "Sandy Wexler",
    "Chewing Gum",
    "The Matchbreaker",
    "Tramps",
    "Slam",
    "Cheer Squad",
    "Almost Adults",
    "The Waterboy",
    "10 Things I Hate About You",
    "Grease",
    "How to Lose a Guy in 10 Days",
    "The Benchwarmers",
    "Step Up",
    "High School Musical 2",
    "Twilight",
    "Coraline",
    "Hannah Montana: The Movie",
    "The Office (U.S.)",
    "Friday Night Lights",
    "StarStruck",
    "Grey's Anatomy",
    "Prison Break",
    "90210",
    "Gossip Girl",
    "How I Met Your Mother",
    "Glee",
    "The Vampire Diaries",
    "Family Guy",
    "Criminal Minds",
    "Friends",
    "Mean Girls 2",
    "The Secret Life of the American Teenager",
    "That '70s Show",
    "Gilmore Girls",
    "Parenthood",
    "Heartland",
    "Pretty Little Liars",
    "Shameless (U.S.)",
    "Switched at Birth",
    "New Girl",
    "Hart of Dixie",
    "The Client List",
    "The Carrie Diaries",
    "Safe Haven",
    "Baby Daddy",
    "The Night Shift",
    "Reign",
    "Grace and Frankie",
    "How to Get Away with Murder",
    "Fuller House",
    "Finding Dory",
    "Gilmore Girls: A Year in the Life",
    "13 Reasons Why",
    "Gabriel lglesias: Iâ€™m Sorry For What I Said When I Was Hungry",
    "Amy Schumer: The Leather Special",
    "Cheer Squad",
    "Dave Chappelle",
    "The Waterboy",
    "Grease",
    "The Wedding Planner",
    "Blow",
    "High School Musical",
    "High School Musical 2",
    "Twilight",
    "Hannah Montana: The Movie",
    "The Office (U.S.)",
    "Bones",
    "Law & Order: Special Victims Unit",
    "Prison Break",
    "Nurse Jackie",
    "NCIS",
    "Gossip Girl",
    "How I Met Your Mother",
    "Supernatural",
    "Parks and Recreation",
    "Glee",
    "The Vampire Diaries",
    "Criminal Minds",
    "Friends",
    "Mean Girls 2",
    "The Secret Life of the American Teenager",
    "One Tree Hill",
    "Army Wives",
    "Gilmore Girls",
    "Private Practice",
    "Parenthood",
    "Pretty Little Liars",
    "Shameless (U.S.)",
    "New Girl",
    "Revenge",
    "Scandal",
    "Magic Mike",
    "Trouble with the Curve",
    "Orange Is the New Black",
    "Baby Daddy",
    "The Night Shift",
    "The Originals",
    "Home",
    "How to Get Away with Murder",
    "Zootopia",
    "Finding Dory",
    "Sausage Party",
    "Skin Wars",
    "Girlboss",
    "13 Reasons Why",
    "Felipe Neto: My Life Makes No Sense",
    "Cheer Squad",
    "Lost",
    "Weeds",
    "The Tudors",
    "Grey's Anatomy",
    "Lie to Me",
    "Prison Break",
    "Gossip Girl",
    "Glee",
    "The Vampire Diaries",
    "The Secret Life of the American Teenager",
    "Drop Dead Diva",
    "Gilmore Girls",
    "Charmed",
    "White Collar",
    "House of Cards",
    "Pretty Little Liars",
    "The Killing",
    "Shameless (U.S.)",
    "Hart of Dixie",
    "Once Upon a Time",
    "Scandal",
    "The Client List",
    "Unconditional",
    "Bates Motel",
    "The Blacklist",
    "The Fosters",
    "Reign",
    "The Originals",
    "The 100",
    "Witches of East End",
    "Bitten",
    "London Has Fallen",
    "Marvel's Jessica Jones",
    "Bloodline",
    "Grace and Frankie",
    "Velvet",
    "How to Get Away with Murder",
    "The Crown",
    "Jane The Virgin",
    "Kurt Seyit & Sura",
    "The Returned",
    "The Girl in the Book",
    "Quantico",
    "Life in Pieces",
    "Ingobernable",
    "Girlboss",
    "13 Reasons Why",
    "MerlÃ­",
    "Greenleaf",
    "100 Metros",
    "Bones",
    "Dexter",
    "Leverage",
    "Grey's Anatomy",
    "Lie to Me",
    "Prison Break",
    "NCIS",
    "Burn Notice",
    "Breaking Bad",
    "Criminal Minds",
    "White Collar",
    "Luther",
    "Hawaii Five-0",
    "House of Cards",
    "Last Man Standing",
    "Revenge",
    "Person of Interest",
    "Scandal",
    "Touch",
    "Sherlock",
    "Breakout Kings",
    "The Client List",
    "Arrow",
    "The Following",
    "Drugs, Inc.",
    "Longmire",
    "Ripper Street",
    "The Fall",
    "Death in Paradise",
    "Marvel's Agents of S.H.I.E.L.D.",
    "Crossing Lines",
    "London Has Fallen",
    "Halt and Catch Fire",
    "Marvel's Iron Fist",
    "The Honorable Woman",
    "Transporter: The Series",
    "Gotham",
    "Better Call Saul",
    "How to Get Away with Murder",
    "Narcos",
    "American Odyssey",
    "Aquarius",
    "Hap and Leonard",
    "Rosewood",
    "Quantico",
    "Limitless",
    "Travelers",
    "The Doctor Blake Mysteries",
    "I.T",
    "Bordertown",
    "The Office (U.S.)",
    "Grey's Anatomy",
    "Law & Order: Special Victims Unit",
    "Lie to Me",
    "Prison Break",
    "90210",
    "Gossip Girl",
    "How I Met Your Mother",
    "Parks and Recreation",
    "The Vampire Diaries",
    "Criminal Minds",
    "Friends",
    "The West Wing",
    "Parenthood",
    "White Collar",
    "Blue Bloods",
    "House of Cards",
    "Pretty Little Liars",
    "The Killing",
    "Shameless (U.S.)",
    "New Girl",
    "Revenge",
    "Person of Interest",
    "Once Upon a Time",
    "Scandal",
    "Forensic Files",
    "Sherlock",
    "The Client List",
    "Orange Is the New Black",
    "Rectify",
    "Black Mirror",
    "Bates Motel",
    "The Fall",
    "The Blacklist",
    "Being Mary Jane: The Series",
    "American Crime",
    "Madam Secretary",
    "Sense8",
    "Scream",
    "Rosewood",
    "The Great British Baking Show",
    "Quantico",
    "Limitless",
    "American Crime Story: The People v. O.J. Simpson",
    "Santa Clarita Diet",
    "No Tomorrow",
    "Girlboss",
    "13 Reasons Why",
    "The Doctor Blake Mysteries",
    "Greenleaf",
    "The Nightmare Before Christmas",
    "Scooby-Doo",
    "Chicken Little",
    "Teenage Mutant Ninja Turtles",
    "Star Wars: The Clone Wars",
    "Coraline",
    "The Smurfs and the Magic Flute",
    "We're Back! A Dinosaur's Story",
    "Thomas & Friends: Thomas & the Runaway Kite",
    "Dino Squad",
    "Cars Toons: Mater's Tall Tales",
    "LeapFrog: The Amazing Alphabet Amusement Park",
    "Star Wars: The Clone Wars",
    "Phineas and Ferb",
    "The Batman",
    "Justice League",
    "Justice League Unlimited",
    "Mighty Morphin Power Rangers",
    "Young Justice",
    "The Super Mario Bros. Super Show!",
    "Power Rangers Zeo",
    "Oscar's Oasis",
    "Transformers Prime",
    "The Adventures of Chuck & Friends",
    "Transformers: Rescue Bots",
    "Thomas & Friends: King of the Railway",
    "LEGO: Marvel Super Heroes: Maximum Overload",
    "Max Steel",
    "Transformers Prime Beast Hunters: Predacons Rising",
    "Agent F.O.X.",
    "VeggieTales in the House",
    "Thunder and the House Of Magic",
    "All Hail King Julien",
    "Kong: King of the Apes",
    "Marvel Super Hero Adventures: Frost Fight!",
    "Slugterra: Slug Fu Showdown",
    "Dinotrux",
    "Edgar Rice Burroughs' Tarzan and Jane",
    "Lego DC Comics: Batman Be-Leaguered",
    "Trollhunters",
    "Power Rangers Dino Charge",
    "Bunks",
    "The Jungle Book",
    "The Angry Birds Movie",
    "The Secret Life of Pets",
    "The Furchester Hotel",
    "Marvel's Hulk: Where Monsters Dwell",
    "Angry Birds",
    "Talking Tom and Friends",
    "Nexo Knights",
    "The Nightmare Before Christmas",
    "An Extremely Goofy Movie",
    "Scooby-Doo",
    "The Iron Giant",
    "Star Wars: The Clone Wars",
    "Cars Toons: Mater's Tall Tales",
    "The Batman",
    "Justice League",
    "Justice League Unlimited",
    "The Cat in the Hat Knows a Lot About That!",
    "Mighty Morphin Power Rangers",
    "Bob the Builder",
    "Beyblade: Metal Fusion",
    "Ninja Turtles: The Next Mutation",
    "Transformers Prime",
    "DreamWorks Kung Fu Panda Awesome Secrets",
    "LEGO Ninjago: Masters of Spinjitzu",
    "Transformers: Rescue Bots",
    "Goosebumps",
    "LEGO Ninjago: Masters of Spinjitzu: Way of the Ninja",
    "Super Buddies",
    "Tad: The Lost Explorer",
    "PokÃ©mon: Indigo League",
    "Ratchet and Clank",
    "Pac-Man and the Ghostly Adventures",
    "Iron Man & Captain America: Heroes United",
    "Power Rangers Super Megaforce",
    "Chuggington",
    "All Hail King Julien",
    "The Adventures of Puss in Boots",
    "Kong: King of the Apes",
    "Marvel Super Hero Adventures: Frost Fight!",
    "Some Assembly Required",
    "Dinotrux",
    "Edgar Rice Burroughs' Tarzan and Jane",
    "Kulipari: An Army of Frogs",
    "Transformers: Robots in Disguise",
    "Robocar Poli",
    "LEGO Bionicle: The Journey to One",
    "Lego DC Comics: Batman Be-Leaguered",
    "Voltron: Legendary Defender",
    "Trollhunters",
    "Buddy Thunderstruck",
    "Power Rangers Dino Charge",
    "PokÃ©mon: XY",
    "Power Rangers Dino Super Charge",
    "The Deep",
    "Skylanders Academy",
    "Marvel's Hulk: Where Monsters Dwell",
    "Growing Up Wild",
    "The Little Rascals",
    "Flubber",
    "Tarzan",
    "The Emperor's New Groove",
    "Scooby-Doo",
    "Lilo & Stitch",
    "Scooby-Doo 2: Monsters Unleashed",
    "The Three Musketeers",
    "Mickey's Twice Upon a Christmas",
    "The Pacifier",
    "Chicken Little",
    "Teenage Mutant Ninja Turtles",
    "Bee Movie",
    "Kung Fu Panda",
    "Coraline",
    "Cars Toons: Mater's Tall Tales",
    "Phineas and Ferb",
    "Super Why!",
    "Jessie",
    "Disney Animation Collection: Vol. 1: Mickey and the Beanstalk",
    "Lab Rats",
    "Masha and the Bear",
    "Pocoyo",
    "Home",
    "Chuggington",
    "Octonauts",
    "Dragons: Race to the Edge",
    "Mother Goose Club",
    "Little Einsteins",
    "Hotel Transylvania 2",
    "Dawn of the Croods",
    "Dinotrux",
    "Goosebumps",
    "Kung Fu Panda 3",
    "Zootopia",
    "The Jungle Book",
    "Home: Adventures with Tip & Oh",
    "Open Season: Scared Silly",
    "The Land Before Time XIV: Journey of the Brave",
    "The Angry Birds Movie",
    "Alice Through the Looking Glass",
    "Finding Dory",
    "The Secret Life of Pets",
    "Ask the StoryBots",
    "The Furchester Hotel",
    "Goldie & Bear",
    "Little Baby Bum: Nursery Rhyme Friends",
    "Angry Birds",
    "Tayo the Little Bus",
    "Talking Tom and Friends",
    "The Little Rascals",
    "Antz",
    "Tarzan",
    "An Extremely Goofy Movie",
    "Chicken Run",
    "The Emperor's New Groove",
    "Lilo & Stitch",
    "Spy Kids 3: Game Over",
    "Annie",
    "Mulan 2",
    "Chicken Little",
    "Lilo & Stitch 2: Stitch Has A Glitch",
    "Teenage Mutant Ninja Turtles",
    "Bee Movie",
    "Kung Fu Panda",
    "Cars Toons: Mater's Tall Tales",
    "Super Why!",
    "DreamWorks Shrek's Swamp Stories",
    "Beverly Hills Chihuahua 3: Viva La Fiesta!",
    "DreamWorks Spooky Stories: Volume 2",
    "The Magic School Bus",
    "Goosebumps",
    "Sammy 2",
    "Disney Animation Collection: Vol. 1: Mickey and the Beanstalk",
    "Masha and the Bear",
    "Pocoyo",
    "Sofia the First",
    "Barbie Life in the Dreamhouse",
    "Paddington",
    "Larva",
    "Sid the Science Kid",
    "Chuggington",
    "All Hail King Julien",
    "Octonauts",
    "Minions",
    "Dragons: Race to the Edge",
    "Little Einsteins",
    "Hotel Transylvania 2",
    "Dinotrux",
    "The Little Prince",
    "Word Party",
    "Zootopia",
    "The Jungle Book",
    "Home: Adventures with Tip & Oh",
    "Open Season: Scared Silly",
    "The Angry Birds Movie",
    "Finding Dory",
    "The Secret Life of Pets",
    "Goldie & Bear",
    "Talking Tom and Friends",
    "Cool Runnings",
    "Homeward Bound: The Incredible Journey",
    "The Little Rascals",
    "Anastasia",
    "Tarzan",
    "The Emperor's New Groove",
    "Scooby-Doo",
    "Lilo & Stitch",
    "Missione Hamburger",
    "Chicken Little",
    "Curious George",
    "Bee Movie",
    "Kung Fu Panda",
    "Coraline",
    "Cars Toons: Mater's Tall Tales",
    "Super Why!",
    "Jessie",
    "Secret of the Wings",
    "The Magic School Bus",
    "Sammy 2",
    "Masha and the Bear",
    "Sofia the First",
    "Barbie Life in the Dreamhouse",
    "Clifford the Big Red Dog",
    "Home",
    "Paddington",
    "Chuggington",
    "Octonauts",
    "Minions",
    "Dragons: Race to the Edge",
    "Little Einsteins",
    "Hotel Transylvania 2",
    "Dinotrux",
    "Walt Disney Animation Studios Short Films Collection",
    "Kung Fu Panda 3",
    "Bunk'd",
    "Zootopia",
    "The Jungle Book",
    "Open Season: Scared Silly",
    "The Land Before Time XIV: Journey of the Brave",
    "The Angry Birds Movie",
    "Alice Through the Looking Glass",
    "The BFG",
    "The Secret Life of Pets",
    "Pete's Dragon",
    "Kubo and the Two Strings",
    "Goldie & Bear",
    "Little Baby Bum: Nursery Rhyme Friends",
    "Growing Up Wild",
    "The Real Ghostbusters",
    "Cool Runnings",
    "Anastasia",
    "Antz",
    "Babe: Pig in the City",
    "The Prince of Egypt",
    "Paulie",
    "Tarzan",
    "The Road to El Dorado",
    "Fantasia 2000",
    "Pocahontas II: Journey to a New World",
    "The Emperor's New Groove",
    "Fantasia",
    "An American Tail",
    "Pooh's Grand Adventure: The Search for Christopher Robin",
    "FernGully 2: The Magical Rescue",
    "Balto 2: Wolf Quest",
    "Balto",
    "Back to the Secret Garden",
    "The Brave Little Toaster Goes to Mars",
    "The Brave Little Toaster to the Rescue",
    "An American Tail: The Mystery of the Night Monster",
    "An American Tail: Fievel Goes West",
    "The Last Unicorn",
    "The Iron Giant",
    "Brother Bear 2",
    "The Fox and the Hound 2",
    "The Smurfs and the Magic Flute",
    "Jetsons: The Movie",
    "We're Back! A Dinosaur's Story",
    "A Monster in Paris",
    "The Gruffalo",
    "DreamWorks How to Train Your Dragon Legends",
    "Ernest & Celestine",
    "The Magic School Bus",
    "Animaniacs",
    "Disney Animation Collection: Vol. 4: The Tortoise and the Hare",
    "PopPixie",
    "Jack and the Cuckoo-Clock Heart",
    "The Pirate Fairy",
    "Axel: The Biggest Little Hero",
    "The Adventures of Figaro Pho",
    "The Boxcar Children",
    "Pet Pals in Windland",
    "Walt Disney Animation Studios Short Films Collection",
    "Alpha and Omega: Dino Digs",
    "Alice Through the Looking Glass",
    "Quackerz",
    "Hatched",
    "Blinky Bill: The Movie",
    "The Real Ghostbusters",
    "Flubber",
    "Anastasia",
    "An Extremely Goofy Movie",
    "An American Tail",
    "Scooby-Doo",
    "FernGully: The Last Rainforest",
    "Balto 2: Wolf Quest",
    "Balto",
    "The Lizzie McGuire Movie",
    "The Brave Little Toaster Goes to Mars",
    "The Brave Little Toaster to the Rescue",
    "Recess: Taking the Fifth Grade",
    "An American Tail: The Mystery of the Night Monster",
    "An American Tail: Fievel Goes West",
    "The Iron Giant",
    "The Very Hungry Caterpillar and Other Stories",
    "The Hero of Color City",
    "Dino Squad",
    "The Little Engine That Could",
    "Delhi Safari",
    "Ninja Turtles: The Next Mutation",
    "Pound Puppies",
    "Sammy 2",
    "Monster Math Squad",
    "Care Bears: Welcome to Care-a-Lot",
    "Clifford the Big Red Dog",
    "Clifford's Puppy Days",
    "Axel: The Biggest Little Hero",
    "Agent F.O.X.",
    "Dinosaur King",
    "Ribbit",
    "Chuggington",
    "Rooster Doodle-doo",
    "Octonauts",
    "Kong: King of the Apes",
    "My Animal Friends",
    "Worms",
    "Puffin Rock",
    "Little Einsteins",
    "Hotel Transylvania 2",
    "Dinotrux",
    "The Mr. Peabody and Sherman Show",
    "Zoobabu",
    "Alpha and Omega: Dino Digs",
    "Gon",
    "Sid the Science Kid: The Movie",
    "The Land Before Time XIV: Journey of the Brave",
    "The Secret Life of Pets",
    "LEGO Jurassic World: The Indominus Escape",
    "The Real Ghostbusters",
    "Cool Runnings",
    "Anastasia",
    "Antz",
    "Babe: Pig in the City",
    "The Prince of Egypt",
    "Paulie",
    "Tarzan",
    "The Road to El Dorado",
    "Fantasia 2000",
    "Pocahontas II: Journey to a New World",
    "The Emperor's New Groove",
    "Fantasia",
    "An American Tail",
    "Pooh's Grand Adventure: The Search for Christopher Robin",
    "FernGully 2: The Magical Rescue",
    "Balto 2: Wolf Quest",
    "Balto",
    "Back to the Secret Garden",
    "The Brave Little Toaster Goes to Mars",
    "The Brave Little Toaster to the Rescue",
    "An American Tail: The Mystery of the Night Monster",
    "An American Tail: Fievel Goes West",
    "The Last Unicorn",
    "The Iron Giant",
    "Brother Bear 2",
    "The Fox and the Hound 2",
    "The Smurfs and the Magic Flute",
    "Jetsons: The Movie",
    "We're Back! A Dinosaur's Story",
    "A Monster in Paris",
    "The Gruffalo",
    "DreamWorks How to Train Your Dragon Legends",
    "Ernest & Celestine",
    "The Magic School Bus",
    "Animaniacs",
    "Disney Animation Collection: Vol. 4: The Tortoise and the Hare",
    "PopPixie",
    "Jack and the Cuckoo-Clock Heart",
    "The Pirate Fairy",
    "Axel: The Biggest Little Hero",
    "The Adventures of Figaro Pho",
    "The Boxcar Children",
    "Pet Pals in Windland",
    "Walt Disney Animation Studios Short Films Collection",
    "Alpha and Omega: Dino Digs",
    "Alice Through the Looking Glass",
    "Quackerz",
    "Hatched",
    "Blinky Bill: The Movie",
    "The Real Ghostbusters",
    "Cool Runnings",
    "Homeward Bound: The Incredible Journey",
    "Anastasia",
    "Antz",
    "Babe: Pig in the City",
    "The Road to El Dorado",
    "Fantasia 2000",
    "Fantasia",
    "Harry and the Hendersons",
    "Pooh's Grand Adventure: The Search for Christopher Robin",
    "Cats & Dogs",
    "Atlantis: The Lost Empire",
    "FernGully: The Last Rainforest",
    "Balto 2: Wolf Quest",
    "Balto",
    "Back to the Secret Garden",
    "Tarzan & Jane",
    "Atlantis: Milo's Return",
    "The Brave Little Toaster Goes to Mars",
    "The Brave Little Toaster to the Rescue",
    "Annie",
    "Recess: Taking the Fifth Grade",
    "An American Tail: The Mystery of the Night Monster",
    "Batched",
    "An American Tail: Fievel Goes West",
    "Winnie the Pooh: Springtime with Roo",
    "The Last Unicorn",
    "The Iron Giant",
    "Mulan 2",
    "Pooh's Heffalump Movie",
    "Kronk's New Groove",
    "Corpse Bride",
    "Brother Bear 2",
    "The Smurfs and the Magic Flute",
    "Jetsons: The Movie",
    "We're Back! A Dinosaur's Story",
    "Ernest & Celestine",
    "Animaniacs",
    "Disney Animation Collection: Vol. 1: Mickey and the Beanstalk",
    "Disney Animation Collection: Vol. 2: Three Little Pigs",
    "Disney Animation Collection: Vol. 4: The Tortoise and the Hare",
    "The Pirate Fairy",
    "Underdogs",
    "The Boxcar Children",
    "Ribbit",
    "Yellowbird",
    "Octonauts",
    "The Land Before Time XIV: Journey of the Brave",
    "Quackerz",
    "Growing Up Wild",
    "Cool Runnings",
    "Mr. Magoo",
    "Flubber",
    "Anastasia",
    "Antz",
    "Babe: Pig in the City",
    "Paulie",
    "The Road to El Dorado",
    "Air Bud: World Pup",
    "An American Tail",
    "Harry and the Hendersons",
    "Cats & Dogs",
    "Baby's Day Out",
    "Balto 2: Wolf Quest",
    "Balto",
    "Back to the Secret Garden",
    "Blank Check",
    "Heavyweights",
    "Inspector Gadget 2",
    "Air Bud: Spikes Back",
    "Annie",
    "An American Tail: Fievel Goes West",
    "D2: The Mighty Ducks",
    "Honey, I Shrunk the Kids",
    "The Iron Giant",
    "The Fox and the Hound 2",
    "Air Buddies",
    "Dr. Dolittle: Tail to the Chief",
    "Flicka 2",
    "H2O: Just Add Water",
    "The Gruffalo",
    "Dolphin Tale",
    "Pound Puppies",
    "Beverly Hills Chihuahua 3: Viva La Fiesta!",
    "The Magic School Bus",
    "Step Dogs",
    "Pokamon: Indigo League",
    "Mia and Me",
    "Paddington",
    "Russell Madness",
    "My Animal Friends",
    "Dawn of the Croods",
    "Alpha and Omega: Dino Digs",
    "Wiener Dog Internationals",
    "Pup Star",
    "The BFG",
    "The Secret Life of Pets",
    "Precious Puppies",
    "Beary Tales",
    "Growing Up Wild",
]
meta_topics = {
    "food": food,
    "sport": sports,
    "person": celebs,
    "movie": movies,
    "book": books,
    "tv show": tv_shows,
    "academic": academic,
    "convo_starters": convo_starters,
}

import random

def select_topic():
    meta_topic = random.choice(list(meta_topics.keys()))
    sub_topic = random.choice(meta_topics[meta_topic])
    
    if meta_topic not in ["convo_starters", "academic"]:
        topic_prompt = f"You want to have a conversation about the {meta_topic} {sub_topic}."
    
    elif meta_topic == academic:
        topic_prompt = f"You want to have a conversation about {sub_topic}"
        
    else:
        topic_prompt = f"You ask, {sub_topic}"
        
    return topic_prompt, meta_topic, sub_topic
